### ISSUE TITLE
hardcoded mdl prefix in sql

### ISSUE THREAD

**Issue by danmarsden** [MoobiEgc/chat_webgd#1]
the "mdl_" prefix is configurable by the Moodle admin - you have hard-coded references to "mdl_" in your sql which should be replaced with curly braces. (see other sql in the code for examples.)

**Comment by danmarsden** [comment]
you're still not doing it quite right - table names should be surrounded by curly braces - the dml moodle functions will automatically add the prefix.
for example this line:
https://github.com/MoobiEgc/chat_webgd/blob/master/chat.php#L53

should be more like
$sql = "SELECT m.user_id,u.firstname 
              FROM {chatwebgd_mensagem} m

**Comment by danmarsden** [comment]
while you're working on those it would also be really good to take a look at our SQL coding style - there are a large number of SQL queries in your code and they are quite hard to read the way you have them written:

https://docs.moodle.org/dev/SQL_coding_style

**Comment by igorpf** [comment]
The SQL query in the line 165 of the file is not working after I refactored the query to use placeholders:
https://github.com/MoobiEgc/chat_webgd/blob/b38e0a7350a8c0cb7e8eb02230a4d1d846818b53/chat.php#L165

The error log from apache shows that the function get_records_sql was supposed to be given 4 parameters instead of 2 (on $params). What is the correct way of using the placeholders?

If I use the '?' placeholder instead of the :nameOfThePlaceholder and repeat the variables in the $params array, the query works, but that's not the best way of doing it. 

It seems that if the placeholders are used more than once it's an error.

Thank you

**Comment by igorpf** [comment]
If I use the '?' placeholder instead of the :nameOfThePlaceholder and repeat the variables in the $params array, the query works, but that's not the best way of doing it.

**Comment by danmarsden** [comment]
each named param within a query must be unique - you cannot use the same param twice.
